export const AJAX_CALL_START = 'AJAX_CALL_START';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

export const PARSE_FILE_SUCCESS = 'PARSE_FILE_SUCCESS';
